name: Feature request
description: Suggest an idea for this project
labels: [ Enhancement, Verification ]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for feature requests only!
        If you have a problem or if you just want to ask a question, please use one of the other templates.
  - type: textarea
    validations:
      required: true
    attributes:
      label: The feature request
      description: >-
        Please provide a clear and concise description of what you want to happen.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: dropdown
    id: device
    validations:
      required: false
    attributes:
      label: Which model do you own?
      options:
        - Deebot 600/601/605
        - Deebot OZMO 610
        - Deebot 710/711/711s
        - Deebot 900/901
        - Deebot OZMO 900/905
        - Deebot OZMO 920
        - Deebot OZMO 930
        - Deebot OZMO 950
        - Deebot OZMO Slim 10/11
        - Deebot U2 series
        - Deebot N3 MAX
        - Deebot N7
        - Deebot N8 series
        - Deebot T8 series
        - Deebot T9 series
        - Deebot Slim 2
        - Deebot N79 series
        - Deebot M88
        - Other model
  - type: input
    id: otherDevice
    validations:
      required: false
    attributes:
      label: Which "other" models are you using?
      placeholder: Deebot [OZMO] xxx
      description: >
        Only required if the model is not listed above ("Which model do you own?") or if you use more than one model with this adapter
  - type: input
    id: version
    validations:
      required: false
    attributes:
      label: Which version of the ioBroker adapter are you currently using?
      placeholder: e.g. 1.1.1, 1.2.2-alpha.1
      description: >
        See state "info.version"
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
